
import { TestCategory, AppSettings } from './types';
import { REFERRING_DOCTORS } from './referringDoctors';

// Increment this version whenever you make structural changes to DEFAULT_TEST_DATA
// to force the app to ignore cached localStorage data and load the new defaults.
export const DATA_VERSION = '2.1'; 

export const DEFAULT_TEST_DATA: TestCategory[] = [
  {
    category: 'CT SCAN-DAY',
    isMajor: true,
    tests: [
      { id: 'ct1', name: 'CT Brain', price: 3000, subcategory: 'Brain & Head', commissionDay: 100, commissionNight: 125 },
      { id: 'ct2', name: 'CT PNS', price: 2500, subcategory: 'Brain & Head', commissionDay: 0, commissionNight: 0 },
      { id: 'ct3', name: 'CT Orbits', price: 3000, subcategory: 'Brain & Head', commissionDay: 0, commissionNight: 0 },
      { id: 'ct4', name: 'CT Face', price: 3000, subcategory: 'Brain & Head', commissionDay: 0, commissionNight: 0 },
      { id: 'ct5', name: '3D Dental Scan', price: 3500, subcategory: 'Brain & Head', commissionDay: 0, commissionNight: 0 },
      { id: 'ct6', name: 'HRCT - Thorax', price: 3500, subcategory: 'Body', commissionDay: 0, commissionNight: 0 },
      { id: 'ct7', name: 'CT Chest', price: 3500, subcategory: 'Body', commissionDay: 0, commissionNight: 0 },
      { id: 'ct8', name: 'CT KUB', price: 3000, subcategory: 'Body', commissionDay: 0, commissionNight: 0 },
      { id: 'ct31', name: 'CT Abdomen - Plain', price: 4000, subcategory: 'Body', commissionDay: 150, commissionNight: 175 },
      { id: 'ct32', name: 'CT Abdomen - Contrast', price: 5000, subcategory: 'Body', commissionDay: 150, commissionNight: 200 },
      { id: 'ct9', name: 'CT Abdomen + Pelvis', price: 4500, subcategory: 'Body', commissionDay: 0, commissionNight: 0 },
      { id: 'ct10', name: 'CT Pelvis', price: 3000, subcategory: 'Body', commissionDay: 0, commissionNight: 0 },
      { id: 'ct11', name: 'CT Neck', price: 3000, subcategory: 'Body', commissionDay: 0, commissionNight: 0 },
      { id: 'ct12', name: 'CT Spine - Cervical', price: 3000, subcategory: 'Spine', commissionDay: 0, commissionNight: 0 },
      { id: 'ct13', name: 'CT Spine - Thoracic', price: 3000, subcategory: 'Spine', commissionDay: 0, commissionNight: 0 },
      { id: 'ct14', name: 'CT Spine - Lumbar', price: 3000, subcategory: 'Spine', commissionDay: 0, commissionNight: 0 },
      { id: 'ct15', name: 'CT Angio - Pulmonary', price: 6000, subcategory: 'Angiography', commissionDay: 0, commissionNight: 0 },
      { id: 'ct16', name: 'CT Angio - Cerebral', price: 6000, subcategory: 'Angiography', commissionDay: 0, commissionNight: 0 },
      { id: 'ct17', name: 'CT Angio - Head & Neck', price: 6000, subcategory: 'Angiography', commissionDay: 0, commissionNight: 0 },
      { id: 'ct18', name: 'CT Angio - Peripheral', price: 7000, subcategory: 'Angiography', commissionDay: 0, commissionNight: 0 },
      { id: 'ct19', name: 'CT Angio - Aortic', price: 7000, subcategory: 'Angiography', commissionDay: 0, commissionNight: 0 },
      { id: 'ct20', name: '3D CT Joints - Hip', price: 3500, subcategory: 'Joints/Limbs', commissionDay: 0, commissionNight: 0 },
      { id: 'ct21', name: '3D CT Joints - Knee', price: 3500, subcategory: 'Joints/Limbs', commissionDay: 0, commissionNight: 0 },
      { id: 'ct22', name: '3D CT Joints - Ankle', price: 3500, subcategory: 'Joints/Limbs', commissionDay: 0, commissionNight: 0 },
      { id: 'ct23', name: '3D CT Joints - Shoulder', price: 3500, subcategory: 'Joints/Limbs', commissionDay: 0, commissionNight: 0 },
      { id: 'ct24', name: '3D CT Joints - Elbow', price: 3500, subcategory: 'Joints/Limbs', commissionDay: 0, commissionNight: 0 },
      { id: 'ct25', name: '3D CT Joints - Wrist', price: 3500, subcategory: 'Joints/Limbs', commissionDay: 0, commissionNight: 0 },
      { id: 'ct26', name: 'CT Limbs - Upper', price: 3000, subcategory: 'Joints/Limbs', commissionDay: 0, commissionNight: 0 },
      { id: 'ct27', name: 'CT Limbs - Lower', price: 3000, subcategory: 'Joints/Limbs', commissionDay: 0, commissionNight: 0 },
      { id: 'ct28', name: 'Brain Perfusion Study', price: 5000, subcategory: 'Special', commissionDay: 0, commissionNight: 0 },
      { id: 'ct29', name: 'CT Urogram', price: 5500, subcategory: 'Special', commissionDay: 0, commissionNight: 0 },
      { id: 'ct30', name: '3D Reconstruction', price: 1000, subcategory: 'Special', commissionDay: 0, commissionNight: 0 },
    ],
  },
  {
    category: 'XRAY',
    isMajor: true,
    tests: [
      { id: 'x1', name: 'Chest PA View', price: 550, commissionDay: 50, commissionNight: 75 },
      { id: 'x2', name: 'KUB X-Ray', price: 400, commissionDay: 0, commissionNight: 0 },
      { id: 'x3', name: 'Abdomen Erect', price: 400, commissionDay: 0, commissionNight: 0 },
      { id: 'x4', name: 'Cervical Spine AP/Lat', price: 550, commissionDay: 50, commissionNight: 100 },
      { id: 'x13', name: 'Pelvis AP and Lateral', price: 550, commissionDay: 50, commissionNight: 125 },
      { id: 'x5', name: 'Skull AP/Lat', price: 500, commissionDay: 0, commissionNight: 0 },
      { id: 'x6', name: 'Barium meal follow through', price: 1500, subcategory: 'Procedures', commissionDay: 0, commissionNight: 0 },
      { id: 'x7', name: 'Hystero salpingography (HSG)', price: 1500, subcategory: 'Procedures', commissionDay: 0, commissionNight: 0 },
      { id: 'x8', name: 'IVU / IVP', price: 2000, subcategory: 'Procedures', commissionDay: 0, commissionNight: 0 },
      { id: 'x9', name: 'Retrograde urography (RGU)', price: 2000, subcategory: 'Procedures', commissionDay: 0, commissionNight: 0 },
      { id: 'x10', name: 'MCU', price: 2000, subcategory: 'Procedures', commissionDay: 0, commissionNight: 0 },
      { id: 'x11', name: 'Sinogram / Fistulogram', price: 1200, subcategory: 'Procedures', commissionDay: 0, commissionNight: 0 },
      { id: 'x12', name: 'Barium swallow', price: 1000, subcategory: 'Procedures', commissionDay: 0, commissionNight: 0 },
    ],
  },
  {
    category: 'CARDIAC',
    isMajor: true,
    tests: [
      { id: 'c1', name: 'ECG', price: 250, commissionDay: 50, commissionNight: 75 },
      { id: 'c2', name: '2D - Echo', price: 1200, commissionDay: 100, commissionNight: 125 },
    ]
  },
  {
    category: 'ULTRASONOGRAPHY',
    isMajor: true,
    tests: [
      { id: 'us22', name: 'USG Abdomen', price: 900, subcategory: 'General Imaging', commissionDay: 100, commissionNight: 125 },
      { id: 'us1', name: 'USG Pelvis', price: 800, subcategory: 'General Imaging', commissionDay: 0, commissionNight: 0 },
      { id: 'us2', name: 'USG Abdomen & Pelvis', price: 1200, subcategory: 'General Imaging', commissionDay: 0, commissionNight: 0 },
      { id: 'us3', name: 'USG KUB', price: 800, subcategory: 'General Imaging', commissionDay: 0, commissionNight: 0 },
      { id: 'us4', name: 'USG Chest', price: 800, subcategory: 'General Imaging', commissionDay: 0, commissionNight: 0 },
      { id: 'us5', name: 'Neurosonogram', price: 1000, subcategory: 'General Imaging', commissionDay: 0, commissionNight: 0 },
      { id: 'us6', name: 'Follicular Study', price: 500, subcategory: 'General Imaging', commissionDay: 0, commissionNight: 0 },
      { id: 'us23', name: 'Doppler (General)', price: 1500, subcategory: 'General Imaging', commissionDay: 175, commissionNight: 200 },
      { id: 'us7', name: 'Early pregnancy', price: 1000, subcategory: 'OBG Scanning', commissionDay: 0, commissionNight: 0 },
      { id: 'us8', name: 'NT scan (11 - 14 weeks)', price: 1200, subcategory: 'OBG Scanning', commissionDay: 150, commissionNight: 175 },
      { id: 'us9', name: 'TIFFA / Anomaly scan', price: 2000, subcategory: 'OBG Scanning', commissionDay: 0, commissionNight: 0 },
      { id: 'us10', name: 'OBG 3D/4D live scan', price: 2000, subcategory: 'OBG Scanning', commissionDay: 175, commissionNight: 175 },
      { id: 'us11', name: 'Routine obstetric', price: 1000, subcategory: 'OBG Scanning', commissionDay: 0, commissionNight: 0 },
      { id: 'us12', name: 'Obstetric Doppler', price: 1800, subcategory: 'OBG Scanning', commissionDay: 0, commissionNight: 0 },
      { id: 'us13', name: 'Fetal biophysical profile (BBP)', price: 1800, subcategory: 'OBG Scanning', commissionDay: 175, commissionNight: 225 },
      { id: 'us14', name: 'USG Thyroid', price: 1000, subcategory: 'HRUS / Small Parts', commissionDay: 0, commissionNight: 0 },
      { id: 'us15', name: 'USG Neck', price: 1000, subcategory: 'HRUS / Small Parts', commissionDay: 0, commissionNight: 0 },
      { id: 'us16', name: 'USG Breast', price: 1200, subcategory: 'HRUS / Small Parts', commissionDay: 0, commissionNight: 0 },
      { id: 'us17', name: 'USG Scrotum / Testes', price: 1000, subcategory: 'HRUS / Small Parts', commissionDay: 0, commissionNight: 0 },
      { id: 'us18', name: 'USG Soft Tissue', price: 800, subcategory: 'HRUS / Small Parts', commissionDay: 0, commissionNight: 0 },
      { id: 'us19', name: 'B Mode Orbits Scan', price: 1000, subcategory: 'HRUS / Small Parts', commissionDay: 0, commissionNight: 0 },
      { id: 'us20', name: 'MSK / Joints - Shoulder', price: 1200, subcategory: 'HRUS / Small Parts', commissionDay: 0, commissionNight: 0 },
      { id: 'us21', name: 'MSK / Joints - Knee', price: 1200, subcategory: 'HRUS / Small Parts', commissionDay: 0, commissionNight: 0 },
      // Colour Doppler Tests moved here as subcategories
      { id: 'cd1', name: 'Carotid Doppler', price: 2000, subcategory: 'COLOUR DOPPLER', commissionDay: 0, commissionNight: 0 },
      { id: 'cd2', name: 'Renal Doppler', price: 2000, subcategory: 'COLOUR DOPPLER', commissionDay: 0, commissionNight: 0 },
      { id: 'cd3', name: 'Abdominal Doppler', price: 2500, subcategory: 'COLOUR DOPPLER', commissionDay: 0, commissionNight: 0 },
      { id: 'cd4', name: 'Arterial Doppler - Right', price: 2000, subcategory: 'COLOUR DOPPLER', commissionDay: 0, commissionNight: 0 },
      { id: 'cd5', name: 'Arterial Doppler - Left', price: 2000, subcategory: 'COLOUR DOPPLER', commissionDay: 0, commissionNight: 0 },
      { id: 'cd6', name: 'Venous Doppler - Right', price: 2000, subcategory: 'COLOUR DOPPLER', commissionDay: 0, commissionNight: 0 },
      { id: 'cd7', name: 'Venous Doppler - Left', price: 2000, subcategory: 'COLOUR DOPPLER', commissionDay: 0, commissionNight: 0 },
      { id: 'cd8', name: 'Upper Limb Doppler', price: 2000, subcategory: 'COLOUR DOPPLER', commissionDay: 0, commissionNight: 0 },
      { id: 'cd9', name: 'Lower Limb Doppler', price: 2000, subcategory: 'COLOUR DOPPLER', commissionDay: 0, commissionNight: 0 },
      { id: 'cd10', name: 'DVT Screening', price: 1800, subcategory: 'COLOUR DOPPLER', commissionDay: 0, commissionNight: 0 },
      { id: 'cd11', name: 'Scrotal Doppler', price: 1500, subcategory: 'COLOUR DOPPLER', commissionDay: 0, commissionNight: 0 },
      // USG Intervention Tests moved here as subcategories
      { id: 'ui1', name: 'Ascitic Tap', price: 1000, subcategory: 'USG INTERVENTION', commissionDay: 0, commissionNight: 0 },
      { id: 'ui2', name: 'Pleural Tap', price: 1000, subcategory: 'USG INTERVENTION', commissionDay: 0, commissionNight: 0 },
      { id: 'ui3', name: 'Intra Articular Injection', price: 1500, subcategory: 'USG INTERVENTION', commissionDay: 0, commissionNight: 0 },
      { id: 'ui4', name: 'USG Guided FNAC', price: 1200, subcategory: 'USG INTERVENTION', commissionDay: 0, commissionNight: 0 },
      { id: 'ui5', name: 'USG Guided Biopsy', price: 2500, subcategory: 'USG INTERVENTION', commissionDay: 0, commissionNight: 0 },
      { id: 'ui6', name: 'USG Guided Abscess Drainage', price: 1500, subcategory: 'USG INTERVENTION', commissionDay: 0, commissionNight: 0 },
      { id: 'ui7', name: 'USG Guided Pig Tail Catheter', price: 2000, subcategory: 'USG INTERVENTION', commissionDay: 0, commissionNight: 0 },
    ],
  },
  {
    category: 'LABORATORY',
    tests: [
      // HAEMATOLOGY
      { id: 'h1', name: 'CBC', price: 250, subcategory: 'HAEMATOLOGY', commissionDay: 50, commissionNight: 50 },
      { id: 'h2', name: 'Hb%', price: 100, subcategory: 'HAEMATOLOGY', commissionDay: 0, commissionNight: 0 },
      { id: 'h3', name: 'TC & DC', price: 150, subcategory: 'HAEMATOLOGY', commissionDay: 0, commissionNight: 0 },
      { id: 'h4', name: 'RBC count', price: 120, subcategory: 'HAEMATOLOGY', commissionDay: 0, commissionNight: 0 },
      { id: 'h5', name: 'Platelet count', price: 150, subcategory: 'HAEMATOLOGY', commissionDay: 0, commissionNight: 0 },
      { id: 'h6', name: 'Complete hemogram', price: 450, subcategory: 'HAEMATOLOGY', commissionDay: 0, commissionNight: 0 },
      { id: 'h7', name: 'Peripheral blood smear study', price: 200, subcategory: 'HAEMATOLOGY', commissionDay: 0, commissionNight: 0 },
      { id: 'h8', name: 'ESR', price: 100, subcategory: 'HAEMATOLOGY', commissionDay: 0, commissionNight: 0 },
      { id: 'h9', name: 'Absolute eosinophil count', price: 180, subcategory: 'HAEMATOLOGY', commissionDay: 0, commissionNight: 0 },
      { id: 'h10', name: 'Reticulocyte count', price: 250, subcategory: 'HAEMATOLOGY', commissionDay: 0, commissionNight: 0 },
      { id: 'h11', name: 'Blood group & Rh typing', price: 100, subcategory: 'HAEMATOLOGY', commissionDay: 0, commissionNight: 0 },

      // CLINICAL PATHOLOGY
      { id: 'cp1', name: 'Urine routine & Microscopy', price: 100, subcategory: 'CLINICAL PATHOLOGY', commissionDay: 10, commissionNight: 10 },
      { id: 'cp2', name: 'Urine for microalbuminurea', price: 300, subcategory: 'CLINICAL PATHOLOGY', commissionDay: 0, commissionNight: 0 },
      { id: 'cp3', name: 'Urine sugar', price: 50, subcategory: 'CLINICAL PATHOLOGY', commissionDay: 0, commissionNight: 0 },
      { id: 'cp4', name: 'Urine Bile salt / Bile pigment', price: 100, subcategory: 'CLINICAL PATHOLOGY', commissionDay: 0, commissionNight: 0 },
      { id: 'cp5', name: 'Urine ketone bodies', price: 100, subcategory: 'CLINICAL PATHOLOGY', commissionDay: 0, commissionNight: 0 },
      { id: 'cp6', name: 'Urine 24 hrs Protein', price: 350, subcategory: 'CLINICAL PATHOLOGY', commissionDay: 0, commissionNight: 0 },
      { id: 'cp7', name: 'Pregnancy test (urine)', price: 150, subcategory: 'CLINICAL PATHOLOGY', commissionDay: 0, commissionNight: 0 },
      { id: 'cp8', name: 'PAP smear', price: 500, subcategory: 'CLINICAL PATHOLOGY', commissionDay: 0, commissionNight: 0 },
      { id: 'cp9', name: 'Semen analysis', price: 350, subcategory: 'CLINICAL PATHOLOGY', commissionDay: 0, commissionNight: 0 },
      { id: 'cp10', name: 'Stool occult blood', price: 200, subcategory: 'CLINICAL PATHOLOGY', commissionDay: 0, commissionNight: 0 },
      { id: 'cp11', name: 'Stool routine (ova&cyst)', price: 200, subcategory: 'CLINICAL PATHOLOGY', commissionDay: 0, commissionNight: 0 },

      // ENDOCRINOLOGY & SPECIAL TESTS
      { id: 'es1', name: 'T3 T4 TSH', price: 800, subcategory: 'ENDOCRINOLOGY', commissionDay: 0, commissionNight: 0 },
      { id: 'es2', name: 'TSH', price: 350, subcategory: 'ENDOCRINOLOGY', commissionDay: 0, commissionNight: 0 },
      { id: 'es3', name: 'Free T3, free T4, TSH', price: 1200, subcategory: 'ENDOCRINOLOGY', commissionDay: 0, commissionNight: 0 },
      { id: 'es4', name: 'Free T3, free T4', price: 900, subcategory: 'ENDOCRINOLOGY', commissionDay: 0, commissionNight: 0 },
      { id: 'es5', name: 'TORCH', price: 2500, subcategory: 'ENDOCRINOLOGY', commissionDay: 0, commissionNight: 0 },
      { id: 'es6', name: 'LH', price: 450, subcategory: 'ENDOCRINOLOGY', commissionDay: 0, commissionNight: 0 },
      { id: 'es7', name: 'FSH', price: 450, subcategory: 'ENDOCRINOLOGY', commissionDay: 0, commissionNight: 0 },
      { id: 'es8', name: 'Prolactin', price: 450, subcategory: 'ENDOCRINOLOGY', commissionDay: 0, commissionNight: 0 },
      { id: 'es9', name: 'Testosterone', price: 550, subcategory: 'ENDOCRINOLOGY', commissionDay: 0, commissionNight: 0 },
      { id: 'es10', name: 'AMH', price: 1800, subcategory: 'ENDOCRINOLOGY', commissionDay: 0, commissionNight: 0 },
      { id: 'es11', name: 'Progesterone', price: 500, subcategory: 'ENDOCRINOLOGY', commissionDay: 0, commissionNight: 0 },
      { id: 'es12', name: 'Estradiol (E2) Estriol', price: 500, subcategory: 'ENDOCRINOLOGY', commissionDay: 0, commissionNight: 0 },
      { id: 'es13', name: 'PSA', price: 800, subcategory: 'ENDOCRINOLOGY', commissionDay: 0, commissionNight: 0 },
      { id: 'es14', name: 'B - HCG', price: 600, subcategory: 'ENDOCRINOLOGY', commissionDay: 0, commissionNight: 0 },
      { id: 'es15', name: 'CA - 125', price: 1200, subcategory: 'ENDOCRINOLOGY', commissionDay: 0, commissionNight: 0 },

      // COAGULATION PROFILE
      { id: 'cg1', name: 'Prothrombin time & INR', price: 400, subcategory: 'COAGULATION PROFILE', commissionDay: 0, commissionNight: 0 },
      { id: 'cg2', name: 'APTT', price: 450, subcategory: 'COAGULATION PROFILE', commissionDay: 0, commissionNight: 0 },
      { id: 'cg3', name: 'D - dimer', price: 900, subcategory: 'COAGULATION PROFILE', commissionDay: 0, commissionNight: 0 },
      { id: 'cg4', name: 'BT / CT', price: 150, subcategory: 'COAGULATION PROFILE', commissionDay: 0, commissionNight: 0 },

      // ELECTROLYTES
      { id: 'el1', name: 'Sodium', price: 150, subcategory: 'ELECTROLYTES', commissionDay: 0, commissionNight: 0 },
      { id: 'el2', name: 'Potassium', price: 150, subcategory: 'ELECTROLYTES', commissionDay: 0, commissionNight: 0 },
      { id: 'el3', name: 'Chloride', price: 150, subcategory: 'ELECTROLYTES', commissionDay: 0, commissionNight: 0 },
      { id: 'el4', name: 'Calcium', price: 200, subcategory: 'ELECTROLYTES', commissionDay: 0, commissionNight: 0 },
      { id: 'el5', name: 'Serum Electrolytes (Na, K, Cl)', price: 500, subcategory: 'ELECTROLYTES', commissionDay: 100, commissionNight: 100 },

      // SEROLOGY & MICROBIOLOGY
      { id: 'sm1', name: 'Double Marker Test', price: 2200, subcategory: 'SEROLOGY & MICROBIOLOGY', commissionDay: 0, commissionNight: 0 },
      { id: 'sm2', name: 'Widal test', price: 150, subcategory: 'SEROLOGY & MICROBIOLOGY', commissionDay: 0, commissionNight: 0 },
      { id: 'sm3', name: 'VDRL test', price: 150, subcategory: 'SEROLOGY & MICROBIOLOGY', commissionDay: 0, commissionNight: 0 },
      { id: 'sm4', name: 'HIV', price: 350, subcategory: 'SEROLOGY & MICROBIOLOGY', commissionDay: 75, commissionNight: 75 },
      { id: 'sm5', name: 'HbsAg', price: 300, subcategory: 'SEROLOGY & MICROBIOLOGY', commissionDay: 0, commissionNight: 0 },
      { id: 'sm6', name: 'HCV', price: 600, subcategory: 'SEROLOGY & MICROBIOLOGY', commissionDay: 0, commissionNight: 0 },
      { id: 'sm7', name: 'Dengue', price: 800, subcategory: 'SEROLOGY & MICROBIOLOGY', commissionDay: 0, commissionNight: 0 },
      { id: 'sm8', name: 'Malaria - ROT', price: 200, subcategory: 'SEROLOGY & MICROBIOLOGY', commissionDay: 0, commissionNight: 0 },
      { id: 'sm9', name: 'Weilfelix Test', price: 300, subcategory: 'SEROLOGY & MICROBIOLOGY', commissionDay: 0, commissionNight: 0 },
      { id: 'sm10', name: 'RA factor', price: 350, subcategory: 'SEROLOGY & MICROBIOLOGY', commissionDay: 0, commissionNight: 0 },
      { id: 'sm11', name: 'ASO factor', price: 350, subcategory: 'SEROLOGY & MICROBIOLOGY', commissionDay: 0, commissionNight: 0 },
      { id: 'sm12', name: 'Mantoux test', price: 200, subcategory: 'SEROLOGY & MICROBIOLOGY', commissionDay: 0, commissionNight: 0 },
      { id: 'sm13', name: 'Coombs test', price: 350, subcategory: 'SEROLOGY & MICROBIOLOGY', commissionDay: 0, commissionNight: 0 },
      { id: 'sm14', name: 'PS for Malaria', price: 150, subcategory: 'SEROLOGY & MICROBIOLOGY', commissionDay: 0, commissionNight: 0 },
      { id: 'sm15', name: 'PS for Microfilaria', price: 150, subcategory: 'SEROLOGY & MICROBIOLOGY', commissionDay: 0, commissionNight: 0 },
      { id: 'sm16', name: 'CRP', price: 350, subcategory: 'SEROLOGY & MICROBIOLOGY', commissionDay: 0, commissionNight: 0 },
      { id: 'sm17', name: 'Sputum for AFB', price: 200, subcategory: 'SEROLOGY & MICROBIOLOGY', commissionDay: 0, commissionNight: 0 },
      { id: 'sm18', name: 'Chickenguniya', price: 600, subcategory: 'SEROLOGY & MICROBIOLOGY', commissionDay: 0, commissionNight: 0 },
      { id: 'sm19', name: 'Gram stain', price: 150, subcategory: 'SEROLOGY & MICROBIOLOGY', commissionDay: 0, commissionNight: 0 },
      { id: 'sm20', name: 'Pleural Fluid Analysis', price: 500, subcategory: 'SEROLOGY & MICROBIOLOGY', commissionDay: 0, commissionNight: 0 },
      { id: 'sm21', name: 'Ascitic Fluid Analysis', price: 500, subcategory: 'SEROLOGY & MICROBIOLOGY', commissionDay: 0, commissionNight: 0 },
      { id: 'sm22', name: 'CSF Fluid Analysis', price: 600, subcategory: 'SEROLOGY & MICROBIOLOGY', commissionDay: 0, commissionNight: 0 },
      { id: 'sm23', name: 'Blood C/S', price: 750, subcategory: 'SEROLOGY & MICROBIOLOGY', commissionDay: 0, commissionNight: 0 },
      { id: 'sm24', name: 'Urine C/S', price: 450, subcategory: 'SEROLOGY & MICROBIOLOGY', commissionDay: 0, commissionNight: 0 },
      { id: 'sm25', name: 'Fluids C/S', price: 600, subcategory: 'SEROLOGY & MICROBIOLOGY', commissionDay: 0, commissionNight: 0 },
      { id: 'sm26', name: 'Sputum C/S', price: 600, subcategory: 'SEROLOGY & MICROBIOLOGY', commissionDay: 0, commissionNight: 0 },
      { id: 'sm27', name: 'Pus C/S', price: 600, subcategory: 'SEROLOGY & MICROBIOLOGY', commissionDay: 0, commissionNight: 0 },
      { id: 'sm28', name: 'Fungal C/S', price: 700, subcategory: 'SEROLOGY & MICROBIOLOGY', commissionDay: 0, commissionNight: 0 },
      { id: 'sm29', name: 'Stool C/S', price: 600, subcategory: 'SEROLOGY & MICROBIOLOGY', commissionDay: 0, commissionNight: 0 },

      // BIOCHEMISTRY
      { id: 'b1', name: 'Ferritin', price: 600, subcategory: 'BIOCHEMISTRY', commissionDay: 0, commissionNight: 0 },
      { id: 'b2', name: 'Blood sugar - Fasting', price: 80, subcategory: 'BIOCHEMISTRY', commissionDay: 0, commissionNight: 0 },
      { id: 'b3', name: 'Blood sugar - Post Prandial', price: 80, subcategory: 'BIOCHEMISTRY', commissionDay: 0, commissionNight: 0 },
      { id: 'b4', name: 'Blood sugar - Random', price: 80, subcategory: 'BIOCHEMISTRY', commissionDay: 0, commissionNight: 0 },
      { id: 'b5', name: 'GCT/OGCT', price: 200, subcategory: 'BIOCHEMISTRY', commissionDay: 0, commissionNight: 0 },
      { id: 'b6', name: 'HbA1c', price: 600, subcategory: 'BIOCHEMISTRY', commissionDay: 100, commissionNight: 100 },
      { id: 'b13', name: 'RFT (Renal Function Test)', price: 400, subcategory: 'BIOCHEMISTRY', commissionDay: 100, commissionNight: 100 },
      { id: 'b14', name: 'LFT (Liver Function Test)', price: 600, subcategory: 'BIOCHEMISTRY', commissionDay: 100, commissionNight: 100 },
      { id: 'b7', name: 'Total Cholestral', price: 200, subcategory: 'BIOCHEMISTRY', commissionDay: 0, commissionNight: 0 },
      { id: 'b8', name: 'LDL', price: 250, subcategory: 'BIOCHEMISTRY', commissionDay: 0, commissionNight: 0 },
      { id: 'b9', name: 'HDL', price: 250, subcategory: 'BIOCHEMISTRY', commissionDay: 0, commissionNight: 0 },
      { id: 'b10', name: 'VLDL', price: 250, subcategory: 'BIOCHEMISTRY', commissionDay: 0, commissionNight: 0 },
      { id: 'b11', name: 'Triglycerides', price: 250, subcategory: 'BIOCHEMISTRY', commissionDay: 0, commissionNight: 0 },
      { id: 'b12', name: 'HDL/LDL Ratio', price: 100, subcategory: 'BIOCHEMISTRY', commissionDay: 0, commissionNight: 0 },

      // LIVER FUNCTION TESTS
      { id: 'lft1', name: 'Serum Bilirubin - Direct', price: 150, subcategory: 'LIVER FUNCTION TESTS', commissionDay: 10, commissionNight: 10 },
      { id: 'lft2', name: 'Serum Bilirubin - Indirect', price: 150, subcategory: 'LIVER FUNCTION TESTS', commissionDay: 10, commissionNight: 10 },
      { id: 'lft3', name: 'SGOT', price: 180, subcategory: 'LIVER FUNCTION TESTS', commissionDay: 0, commissionNight: 0 },
      { id: 'lft4', name: 'SGPT', price: 180, subcategory: 'LIVER FUNCTION TESTS', commissionDay: 0, commissionNight: 0 },
      { id: 'lft5', name: 'Alk.Phosphatase', price: 200, subcategory: 'LIVER FUNCTION TESTS', commissionDay: 0, commissionNight: 0 },
      { id: 'lft6', name: 'Total protein', price: 150, subcategory: 'LIVER FUNCTION TESTS', commissionDay: 0, commissionNight: 0 },
      { id: 'lft7', name: 'Albumin', price: 150, subcategory: 'LIVER FUNCTION TESTS', commissionDay: 0, commissionNight: 0 },
      { id: 'lft8', name: 'Globulin', price: 150, subcategory: 'LIVER FUNCTION TESTS', commissionDay: 0, commissionNight: 0 },
      { id: 'lft9', name: 'A/G Ratio', price: 100, subcategory: 'LIVER FUNCTION TESTS', commissionDay: 0, commissionNight: 0 },

      // RENAL FUNCTION TESTS
      { id: 'rft1', name: 'Blood Urea', price: 180, subcategory: 'RENAL FUNCTION TESTS', commissionDay: 0, commissionNight: 0 },
      { id: 'rft2', name: 'Serum Creatinine', price: 180, subcategory: 'RENAL FUNCTION TESTS', commissionDay: 0, commissionNight: 0 },
      { id: 'rft3', name: 'Serum Uric Acid', price: 200, subcategory: 'RENAL FUNCTION TESTS', commissionDay: 0, commissionNight: 0 },
      { id: 'rft4', name: 'Serum Amylase', price: 400, subcategory: 'RENAL FUNCTION TESTS', commissionDay: 0, commissionNight: 0 },
      { id: 'rft5', name: 'Serum Lipase', price: 450, subcategory: 'RENAL FUNCTION TESTS', commissionDay: 0, commissionNight: 0 },
      { id: 'rft6', name: 'Protein - Total & Albumin', price: 250, subcategory: 'RENAL FUNCTION TESTS', commissionDay: 0, commissionNight: 0 },
      { id: 'rft7', name: 'LDH', price: 350, subcategory: 'RENAL FUNCTION TESTS', commissionDay: 0, commissionNight: 0 },
      { id: 'rft8', name: 'ADA', price: 500, subcategory: 'RENAL FUNCTION TESTS', commissionDay: 0, commissionNight: 0 },
      { id: 'rft9', name: 'CK - MB', price: 600, subcategory: 'RENAL FUNCTION TESTS', commissionDay: 0, commissionNight: 0 },
      { id: 'rft10', name: 'Troponin - I', price: 900, subcategory: 'RENAL FUNCTION TESTS', commissionDay: 0, commissionNight: 0 },
    ],
  },
  {
    category: 'HEALTH PACKAGE',
    tests: [
        { id: 'hp1', name: 'Basic health check up', price: 3000, commissionDay: 300, commissionNight: 300 },
        { id: 'hp2', name: 'Master health check up - male', price: 2499, commissionDay: 0, commissionNight: 0 },
        { id: 'hp3', name: 'Master health check up - female', price: 2999, commissionDay: 0, commissionNight: 0 },
        { id: 'hp4', name: 'Pre - operative package', price: 1500, commissionDay: 0, commissionNight: 0 },
        { id: 'hp5', name: 'ANC (Pregnancy) package', price: 1200, commissionDay: 0, commissionNight: 0 },
        { id: 'hp6', name: 'Arogyam', price: 3500, commissionDay: 0, commissionNight: 0 },
    ]
  },
];


export const DEFAULT_SETTINGS: AppSettings = {
    labName: 'SHIVASAI SCANNING, LAB & DIAGNOSTIC CENTER',
    labAddress: 'Jadhav Complex, Near Jadhav Hospital, BHALKI-585 328',
    labContact: 'Ph: 08484-467649 | shivasaiscanning@gmail.com',
    taxRate: 0, // Tax is removed from calculations, so default to 0
    referringDoctors: REFERRING_DOCTORS,
    autoDeleteDays: 45, // 0 to disable
    verificationThreshold: 1000, // Bills above this amount need admin verification
};
